name: Deploy
on: push
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@master
    - name: Wait for CF Pages
      id: cf-pages
      uses: WalshyDev/cf-pages-await@v1
      with:
        apiToken: ${{ secrets.CF_API_TOKEN  }}
        accountId: ${{ vars.CF_ACCOUNT_ID }}
        project: ${{ vars.CF_PROJECT_NAME }}
        # githubToken: ${{ secrets.GITHUB_TOKEN }}
